<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20210402084905 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE account (id INT AUTO_INCREMENT NOT NULL, account_type_id INT DEFAULT NULL, siren VARCHAR(25) NOT NULL, tva VARCHAR(25) DEFAULT NULL, name VARCHAR(100) NOT NULL, phone VARCHAR(15) DEFAULT NULL, address VARCHAR(100) DEFAULT NULL, is_active TINYINT(1) NOT NULL, date_created DATETIME NOT NULL, email VARCHAR(45) DEFAULT NULL, zipcode VARCHAR(15) DEFAULT NULL, city VARCHAR(45) DEFAULT NULL, country VARCHAR(45) DEFAULT NULL, logo VARCHAR(100) DEFAULT NULL, INDEX IDX_7D3656A4C6798DB (account_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE account_default_module (account_id INT NOT NULL, module_id INT NOT NULL, INDEX IDX_B982E9719B6B5FBA (account_id), INDEX IDX_B982E971AFC2B591 (module_id), PRIMARY KEY(account_id, module_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE account_custom_module (account_id INT NOT NULL, module_id INT NOT NULL, INDEX IDX_A7AFCE9F9B6B5FBA (account_id), INDEX IDX_A7AFCE9FAFC2B591 (module_id), PRIMARY KEY(account_id, module_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE account_type (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(45) DEFAULT NULL, description LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE account_type_default_permission (id INT AUTO_INCREMENT NOT NULL, module_id INT DEFAULT NULL, account_type_id INT DEFAULT NULL, permission_id INT DEFAULT NULL, options LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\', INDEX IDX_4456D3E1AFC2B591 (module_id), INDEX IDX_4456D3E1C6798DB (account_type_id), INDEX IDX_4456D3E1FED90CCA (permission_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE alert (id INT AUTO_INCREMENT NOT NULL, alert_type_id INT NOT NULL, alert_status_id INT NOT NULL, vehicule_id INT NOT NULL, form_id INT NOT NULL, account_id INT NOT NULL, created_by_account_id INT NOT NULL, created_by_id INT NOT NULL, treated_by_id INT DEFAULT NULL, description LONGTEXT NOT NULL, comment LONGTEXT NOT NULL, alert_level VARCHAR(45) NOT NULL, priority VARCHAR(45) NOT NULL, severity VARCHAR(45) NOT NULL, is_active TINYINT(1) NOT NULL, is_treated TINYINT(1) NOT NULL, date_treated DATETIME DEFAULT NULL, date_created DATETIME NOT NULL, INDEX IDX_17FD46C15B1F2B51 (alert_type_id), INDEX IDX_17FD46C1DA891D69 (alert_status_id), INDEX IDX_17FD46C14A4A3511 (vehicule_id), INDEX IDX_17FD46C15FF69B7D (form_id), INDEX IDX_17FD46C19B6B5FBA (account_id), INDEX IDX_17FD46C1A832475A (created_by_account_id), INDEX IDX_17FD46C1B03A8386 (created_by_id), INDEX IDX_17FD46C1794E2304 (treated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE alert_intervention (alert_id INT NOT NULL, intervention_id INT NOT NULL, INDEX IDX_1349B9D193035F72 (alert_id), INDEX IDX_1349B9D18EAE3863 (intervention_id), PRIMARY KEY(alert_id, intervention_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE alert_status (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, is_treated INT NOT NULL, is_renotification INT NOT NULL, color VARCHAR(45) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE alert_type (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(45) NOT NULL, template VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE customer (id INT AUTO_INCREMENT NOT NULL, created_by_id INT DEFAULT NULL, account_gestionnaire_id INT DEFAULT NULL, account_customer_id INT DEFAULT NULL, account_affiliated_to_id INT DEFAULT NULL, gestionnaire_id INT DEFAULT NULL, name VARCHAR(100) DEFAULT NULL, is_national_contract TINYINT(1) DEFAULT NULL, is_active TINYINT(1) DEFAULT NULL, date_created DATETIME NOT NULL, INDEX IDX_81398E09B03A8386 (created_by_id), INDEX IDX_81398E098802B2C1 (account_gestionnaire_id), INDEX IDX_81398E0942D23FF0 (account_customer_id), INDEX IDX_81398E09F95FDB7F (account_affiliated_to_id), INDEX IDX_81398E096885AC1B (gestionnaire_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE form (id INT AUTO_INCREMENT NOT NULL, form_template_id INT DEFAULT NULL, customer_id INT DEFAULT NULL, site_id INT DEFAULT NULL, account_id INT DEFAULT NULL, created_by_id INT NOT NULL, vehicule_id INT DEFAULT NULL, name VARCHAR(100) DEFAULT NULL, reference VARCHAR(45) DEFAULT NULL, is_public TINYINT(1) NOT NULL, date_created DATETIME NOT NULL, is_validated TINYINT(1) NOT NULL, nb_error INT DEFAULT NULL, nb_warning INT DEFAULT NULL, title VARCHAR(100) DEFAULT NULL, footer VARCHAR(511) DEFAULT NULL, INDEX IDX_5288FD4FF2B19FA9 (form_template_id), INDEX IDX_5288FD4F9395C3F3 (customer_id), INDEX IDX_5288FD4FF6BD1646 (site_id), INDEX IDX_5288FD4F9B6B5FBA (account_id), INDEX IDX_5288FD4FB03A8386 (created_by_id), INDEX IDX_5288FD4F4A4A3511 (vehicule_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE form_annotation (id INT AUTO_INCREMENT NOT NULL, account_id INT DEFAULT NULL, name VARCHAR(45) DEFAULT NULL, category VARCHAR(45) DEFAULT NULL, INDEX IDX_278372669B6B5FBA (account_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE form_file (id INT AUTO_INCREMENT NOT NULL, form_id INT DEFAULT NULL, form_field_name VARCHAR(100) DEFAULT NULL, file_uuid VARCHAR(45) DEFAULT NULL, file_name VARCHAR(100) DEFAULT NULL, date_created DATETIME NOT NULL, INDEX IDX_18BE32075FF69B7D (form_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE form_record (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, form_id INT DEFAULT NULL, records LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\', date_created DATETIME NOT NULL, INDEX IDX_99DA4B3FA76ED395 (user_id), INDEX IDX_99DA4B3F5FF69B7D (form_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE form_record_file (id INT AUTO_INCREMENT NOT NULL, created_by_id INT DEFAULT NULL, file_name VARCHAR(100) DEFAULT NULL, file_path VARCHAR(100) DEFAULT NULL, date_created DATETIME NOT NULL, lat VARCHAR(45) DEFAULT NULL, lng VARCHAR(45) DEFAULT NULL, INDEX IDX_9E4337D5B03A8386 (created_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE form_record_file_annotation (id INT AUTO_INCREMENT NOT NULL, form_file_id INT DEFAULT NULL, form_annotation_id INT DEFAULT NULL, form_annotation_text VARCHAR(45) DEFAULT NULL, coordinates LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\', comment VARCHAR(100) DEFAULT NULL, INDEX IDX_643D8A33A2A71957 (form_file_id), INDEX IDX_643D8A3343A3BB6B (form_annotation_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE form_template (id INT AUTO_INCREMENT NOT NULL, account_id INT DEFAULT NULL, customer_id INT DEFAULT NULL, form_type_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, name VARCHAR(100) DEFAULT NULL, title VARCHAR(100) DEFAULT NULL, footer VARCHAR(511) DEFAULT NULL, is_public TINYINT(1) NOT NULL, date_created DATETIME NOT NULL, description LONGTEXT DEFAULT NULL, page_name VARCHAR(255) DEFAULT NULL, builder LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\', is_briefing TINYINT(1) NOT NULL, is_active TINYINT(1) NOT NULL, INDEX IDX_265A9AC79B6B5FBA (account_id), INDEX IDX_265A9AC79395C3F3 (customer_id), INDEX IDX_265A9AC7F420ECA8 (form_type_id), INDEX IDX_265A9AC7B03A8386 (created_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE form_type (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE intervention (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE intervention_user (intervention_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_822CCE8B8EAE3863 (intervention_id), INDEX IDX_822CCE8BA76ED395 (user_id), PRIMARY KEY(intervention_id, user_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE intervention_cancel_reason (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE intervention_endform (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE intervention_status (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE module (id INT AUTO_INCREMENT NOT NULL, category_id INT DEFAULT NULL, name VARCHAR(45) DEFAULT NULL, title VARCHAR(45) DEFAULT NULL, short_desc VARCHAR(100) DEFAULT NULL, description LONGTEXT DEFAULT NULL, inheritance INT DEFAULT NULL, icon VARCHAR(45) DEFAULT NULL, is_public TINYINT(1) DEFAULT NULL, public_price DOUBLE PRECISION DEFAULT NULL, price_var VARCHAR(45) NOT NULL, INDEX IDX_C24262812469DE2 (category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE module_category (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(45) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE network (id INT AUTO_INCREMENT NOT NULL, created_by_id INT DEFAULT NULL, account_id INT DEFAULT NULL, name VARCHAR(100) DEFAULT NULL, date_created DATETIME NOT NULL, INDEX IDX_608487BCB03A8386 (created_by_id), INDEX IDX_608487BC9B6B5FBA (account_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE network_account (network_id INT NOT NULL, account_id INT NOT NULL, INDEX IDX_D98581CE34128B91 (network_id), INDEX IDX_D98581CE9B6B5FBA (account_id), PRIMARY KEY(network_id, account_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE notification_log (id INT AUTO_INCREMENT NOT NULL, notification_type_id INT NOT NULL, user_id INT NOT NULL, account_id INT DEFAULT NULL, date_created DATETIME NOT NULL, notification_text VARCHAR(250) NOT NULL, element_id INT NOT NULL, INDEX IDX_ED15DF2D0520624 (notification_type_id), INDEX IDX_ED15DF2A76ED395 (user_id), INDEX IDX_ED15DF29B6B5FBA (account_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE notification_type (id INT AUTO_INCREMENT NOT NULL, permission_id INT NOT NULL, ref VARCHAR(45) NOT NULL, name VARCHAR(45) NOT NULL, parameter_text VARCHAR(255) NOT NULL, defaut INT NOT NULL, category VARCHAR(45) NOT NULL, orders INT NOT NULL, notification_text VARCHAR(250) NOT NULL, defautl_image VARCHAR(255) NOT NULL, route VARCHAR(45) NOT NULL, action VARCHAR(45) NOT NULL, is_active TINYINT(1) NOT NULL, INDEX IDX_34E21C13FED90CCA (permission_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE permission (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, description VARCHAR(255) NOT NULL, date_created DATETIME NOT NULL, is_super_admin_only TINYINT(1) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE refresh_tokens (id INT AUTO_INCREMENT NOT NULL, refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid DATETIME NOT NULL, UNIQUE INDEX UNIQ_9BACE7E1C74F2195 (refresh_token), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE site (id INT AUTO_INCREMENT NOT NULL, customer_id INT DEFAULT NULL, gestionnaire_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, name VARCHAR(100) DEFAULT NULL, phone VARCHAR(15) DEFAULT NULL, cellphone VARCHAR(15) DEFAULT NULL, social_name VARCHAR(100) DEFAULT NULL, siret VARCHAR(45) DEFAULT NULL, address VARCHAR(100) NOT NULL, zipcode VARCHAR(15) DEFAULT NULL, city VARCHAR(45) DEFAULT NULL, country VARCHAR(45) DEFAULT NULL, latitude VARCHAR(45) DEFAULT NULL, longitude VARCHAR(45) DEFAULT NULL, is_active TINYINT(1) DEFAULT NULL, date_created DATETIME NOT NULL, INDEX IDX_694309E49395C3F3 (customer_id), INDEX IDX_694309E46885AC1B (gestionnaire_id), INDEX IDX_694309E4B03A8386 (created_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE site_vehicule (site_id INT NOT NULL, vehicule_id INT NOT NULL, INDEX IDX_256240C7F6BD1646 (site_id), INDEX IDX_256240C74A4A3511 (vehicule_id), PRIMARY KEY(site_id, vehicule_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, account_id INT NOT NULL, user_type_id INT DEFAULT NULL, email VARCHAR(127) NOT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, phone VARCHAR(15) DEFAULT NULL, cellphone VARCHAR(15) DEFAULT NULL, password VARCHAR(255) NOT NULL, is_active TINYINT(1) DEFAULT NULL, is_deleted TINYINT(1) DEFAULT NULL, date_created DATETIME NOT NULL, can_login TINYINT(1) DEFAULT NULL, can_login_app TINYINT(1) DEFAULT NULL, pwd_reset_token VARCHAR(32) DEFAULT NULL, pwd_reset_token_creation_date DATETIME DEFAULT NULL, address LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\', function VARCHAR(100) DEFAULT NULL, enabled TINYINT(1) NOT NULL, confirmation_token VARCHAR(40) DEFAULT NULL, INDEX IDX_8D93D6499B6B5FBA (account_id), INDEX IDX_8D93D6499D419299 (user_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_permission (user_id INT NOT NULL, permission_id INT NOT NULL, INDEX IDX_472E5446A76ED395 (user_id), INDEX IDX_472E5446FED90CCA (permission_id), PRIMARY KEY(user_id, permission_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_notification_type (user_id INT NOT NULL, notification_type_id INT NOT NULL, INDEX IDX_CCFDA738A76ED395 (user_id), INDEX IDX_CCFDA738D0520624 (notification_type_id), PRIMARY KEY(user_id, notification_type_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_group (id INT AUTO_INCREMENT NOT NULL, account_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, name VARCHAR(100) DEFAULT NULL, is_active TINYINT(1) DEFAULT NULL, date_created DATETIME DEFAULT NULL, INDEX IDX_8F02BF9D9B6B5FBA (account_id), INDEX IDX_8F02BF9DB03A8386 (created_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_group_site (user_group_id INT NOT NULL, site_id INT NOT NULL, INDEX IDX_E77E94781ED93D47 (user_group_id), INDEX IDX_E77E9478F6BD1646 (site_id), PRIMARY KEY(user_group_id, site_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_group_network (user_group_id INT NOT NULL, network_id INT NOT NULL, INDEX IDX_80A7EE01ED93D47 (user_group_id), INDEX IDX_80A7EE034128B91 (network_id), PRIMARY KEY(user_group_id, network_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_group_member (id INT AUTO_INCREMENT NOT NULL, user_group_id INT DEFAULT NULL, user_id INT DEFAULT NULL, is_manager TINYINT(1) DEFAULT NULL, INDEX IDX_23AE5EAA1ED93D47 (user_group_id), INDEX IDX_23AE5EAAA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_log_last_read (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, date DATETIME NOT NULL, INDEX IDX_F6F0B4E5A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_login (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, date DATETIME NOT NULL, INDEX IDX_48CA3048A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_type (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(45) NOT NULL, comment VARCHAR(45) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE vehicule (id INT AUTO_INCREMENT NOT NULL, vehicule_detail_id INT DEFAULT NULL, comment VARCHAR(45) DEFAULT NULL, observation LONGTEXT DEFAULT NULL, date_created DATETIME NOT NULL, is_active TINYINT(1) NOT NULL, INDEX IDX_292FFF1D7420A800 (vehicule_detail_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE vehicule_brand (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(45) DEFAULT NULL, comment VARCHAR(45) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE vehicule_carburant (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(45) DEFAULT NULL, comment VARCHAR(45) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE vehicule_category (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(45) DEFAULT NULL, comment VARCHAR(45) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE vehicule_detail (id INT AUTO_INCREMENT NOT NULL, vehicule_category_id INT DEFAULT NULL, vehicule_brand_id INT DEFAULT NULL, vehicule_carburant_id INT DEFAULT NULL, vehicule_type_id INT DEFAULT NULL, immat VARCHAR(10) DEFAULT NULL, vin VARCHAR(20) DEFAULT NULL, vehicule_model_text VARCHAR(45) DEFAULT NULL, name VARCHAR(45) DEFAULT NULL, denom_com VARCHAR(100) DEFAULT NULL, actual_km INT DEFAULT NULL, next_ct DATE DEFAULT NULL, next_cpollution DATE DEFAULT NULL, date_mec DATE DEFAULT NULL, horse_power INT DEFAULT NULL, fisc_power INT DEFAULT NULL, cylindree DOUBLE PRECISION DEFAULT NULL, transmission VARCHAR(45) DEFAULT NULL, nb_seats INT DEFAULT NULL, nb_doors INT DEFAULT NULL, tire_size_rear VARCHAR(20) DEFAULT NULL, tire_size_back VARCHAR(20) DEFAULT NULL, ptac VARCHAR(10) DEFAULT NULL, date_created DATETIME NOT NULL, picture VARCHAR(255) DEFAULT NULL, INDEX IDX_AB5396B354733C01 (vehicule_category_id), INDEX IDX_AB5396B38A72B23 (vehicule_brand_id), INDEX IDX_AB5396B3B9F2B47 (vehicule_carburant_id), INDEX IDX_AB5396B3FEA7F9B2 (vehicule_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE vehicule_file (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, base_dir VARCHAR(100) DEFAULT NULL, file_uuid VARCHAR(45) DEFAULT NULL, file_name VARCHAR(245) DEFAULT NULL, date_created DATETIME NOT NULL, INDEX IDX_E0988DFF727ACA70 (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE vehicule_type (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(45) DEFAULT NULL, comment VARCHAR(45) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE account ADD CONSTRAINT FK_7D3656A4C6798DB FOREIGN KEY (account_type_id) REFERENCES account_type (id)');
        $this->addSql('ALTER TABLE account_default_module ADD CONSTRAINT FK_B982E9719B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE account_default_module ADD CONSTRAINT FK_B982E971AFC2B591 FOREIGN KEY (module_id) REFERENCES module (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE account_custom_module ADD CONSTRAINT FK_A7AFCE9F9B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE account_custom_module ADD CONSTRAINT FK_A7AFCE9FAFC2B591 FOREIGN KEY (module_id) REFERENCES module (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE account_type_default_permission ADD CONSTRAINT FK_4456D3E1AFC2B591 FOREIGN KEY (module_id) REFERENCES module (id)');
        $this->addSql('ALTER TABLE account_type_default_permission ADD CONSTRAINT FK_4456D3E1C6798DB FOREIGN KEY (account_type_id) REFERENCES account_type (id)');
        $this->addSql('ALTER TABLE account_type_default_permission ADD CONSTRAINT FK_4456D3E1FED90CCA FOREIGN KEY (permission_id) REFERENCES permission (id)');
        $this->addSql('ALTER TABLE alert ADD CONSTRAINT FK_17FD46C15B1F2B51 FOREIGN KEY (alert_type_id) REFERENCES alert_type (id)');
        $this->addSql('ALTER TABLE alert ADD CONSTRAINT FK_17FD46C1DA891D69 FOREIGN KEY (alert_status_id) REFERENCES alert_status (id)');
        $this->addSql('ALTER TABLE alert ADD CONSTRAINT FK_17FD46C14A4A3511 FOREIGN KEY (vehicule_id) REFERENCES vehicule (id)');
        $this->addSql('ALTER TABLE alert ADD CONSTRAINT FK_17FD46C15FF69B7D FOREIGN KEY (form_id) REFERENCES form (id)');
        $this->addSql('ALTER TABLE alert ADD CONSTRAINT FK_17FD46C19B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE alert ADD CONSTRAINT FK_17FD46C1A832475A FOREIGN KEY (created_by_account_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE alert ADD CONSTRAINT FK_17FD46C1B03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE alert ADD CONSTRAINT FK_17FD46C1794E2304 FOREIGN KEY (treated_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE alert_intervention ADD CONSTRAINT FK_1349B9D193035F72 FOREIGN KEY (alert_id) REFERENCES alert (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE alert_intervention ADD CONSTRAINT FK_1349B9D18EAE3863 FOREIGN KEY (intervention_id) REFERENCES intervention (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE customer ADD CONSTRAINT FK_81398E09B03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE customer ADD CONSTRAINT FK_81398E098802B2C1 FOREIGN KEY (account_gestionnaire_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE customer ADD CONSTRAINT FK_81398E0942D23FF0 FOREIGN KEY (account_customer_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE customer ADD CONSTRAINT FK_81398E09F95FDB7F FOREIGN KEY (account_affiliated_to_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE customer ADD CONSTRAINT FK_81398E096885AC1B FOREIGN KEY (gestionnaire_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE form ADD CONSTRAINT FK_5288FD4FF2B19FA9 FOREIGN KEY (form_template_id) REFERENCES form_template (id)');
        $this->addSql('ALTER TABLE form ADD CONSTRAINT FK_5288FD4F9395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id)');
        $this->addSql('ALTER TABLE form ADD CONSTRAINT FK_5288FD4FF6BD1646 FOREIGN KEY (site_id) REFERENCES site (id)');
        $this->addSql('ALTER TABLE form ADD CONSTRAINT FK_5288FD4F9B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE form ADD CONSTRAINT FK_5288FD4FB03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE form ADD CONSTRAINT FK_5288FD4F4A4A3511 FOREIGN KEY (vehicule_id) REFERENCES vehicule (id)');
        $this->addSql('ALTER TABLE form_annotation ADD CONSTRAINT FK_278372669B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE form_file ADD CONSTRAINT FK_18BE32075FF69B7D FOREIGN KEY (form_id) REFERENCES form (id)');
        $this->addSql('ALTER TABLE form_record ADD CONSTRAINT FK_99DA4B3FA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE form_record ADD CONSTRAINT FK_99DA4B3F5FF69B7D FOREIGN KEY (form_id) REFERENCES form (id)');
        $this->addSql('ALTER TABLE form_record_file ADD CONSTRAINT FK_9E4337D5B03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE form_record_file_annotation ADD CONSTRAINT FK_643D8A33A2A71957 FOREIGN KEY (form_file_id) REFERENCES form_file (id)');
        $this->addSql('ALTER TABLE form_record_file_annotation ADD CONSTRAINT FK_643D8A3343A3BB6B FOREIGN KEY (form_annotation_id) REFERENCES form_annotation (id)');
        $this->addSql('ALTER TABLE form_template ADD CONSTRAINT FK_265A9AC79B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE form_template ADD CONSTRAINT FK_265A9AC79395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id)');
        $this->addSql('ALTER TABLE form_template ADD CONSTRAINT FK_265A9AC7F420ECA8 FOREIGN KEY (form_type_id) REFERENCES form_type (id)');
        $this->addSql('ALTER TABLE form_template ADD CONSTRAINT FK_265A9AC7B03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE intervention_user ADD CONSTRAINT FK_822CCE8B8EAE3863 FOREIGN KEY (intervention_id) REFERENCES intervention (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE intervention_user ADD CONSTRAINT FK_822CCE8BA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE module ADD CONSTRAINT FK_C24262812469DE2 FOREIGN KEY (category_id) REFERENCES module_category (id)');
        $this->addSql('ALTER TABLE network ADD CONSTRAINT FK_608487BCB03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE network ADD CONSTRAINT FK_608487BC9B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE network_account ADD CONSTRAINT FK_D98581CE34128B91 FOREIGN KEY (network_id) REFERENCES network (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE network_account ADD CONSTRAINT FK_D98581CE9B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notification_log ADD CONSTRAINT FK_ED15DF2D0520624 FOREIGN KEY (notification_type_id) REFERENCES notification_type (id)');
        $this->addSql('ALTER TABLE notification_log ADD CONSTRAINT FK_ED15DF2A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE notification_log ADD CONSTRAINT FK_ED15DF29B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE notification_type ADD CONSTRAINT FK_34E21C13FED90CCA FOREIGN KEY (permission_id) REFERENCES permission (id)');
        $this->addSql('ALTER TABLE site ADD CONSTRAINT FK_694309E49395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id)');
        $this->addSql('ALTER TABLE site ADD CONSTRAINT FK_694309E46885AC1B FOREIGN KEY (gestionnaire_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE site ADD CONSTRAINT FK_694309E4B03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE site_vehicule ADD CONSTRAINT FK_256240C7F6BD1646 FOREIGN KEY (site_id) REFERENCES site (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE site_vehicule ADD CONSTRAINT FK_256240C74A4A3511 FOREIGN KEY (vehicule_id) REFERENCES vehicule (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D6499B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D6499D419299 FOREIGN KEY (user_type_id) REFERENCES user_type (id)');
        $this->addSql('ALTER TABLE user_permission ADD CONSTRAINT FK_472E5446A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_permission ADD CONSTRAINT FK_472E5446FED90CCA FOREIGN KEY (permission_id) REFERENCES permission (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_notification_type ADD CONSTRAINT FK_CCFDA738A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_notification_type ADD CONSTRAINT FK_CCFDA738D0520624 FOREIGN KEY (notification_type_id) REFERENCES notification_type (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_group ADD CONSTRAINT FK_8F02BF9D9B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE user_group ADD CONSTRAINT FK_8F02BF9DB03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user_group_site ADD CONSTRAINT FK_E77E94781ED93D47 FOREIGN KEY (user_group_id) REFERENCES user_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_group_site ADD CONSTRAINT FK_E77E9478F6BD1646 FOREIGN KEY (site_id) REFERENCES site (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_group_network ADD CONSTRAINT FK_80A7EE01ED93D47 FOREIGN KEY (user_group_id) REFERENCES user_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_group_network ADD CONSTRAINT FK_80A7EE034128B91 FOREIGN KEY (network_id) REFERENCES network (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_group_member ADD CONSTRAINT FK_23AE5EAA1ED93D47 FOREIGN KEY (user_group_id) REFERENCES user_group (id)');
        $this->addSql('ALTER TABLE user_group_member ADD CONSTRAINT FK_23AE5EAAA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user_log_last_read ADD CONSTRAINT FK_F6F0B4E5A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user_login ADD CONSTRAINT FK_48CA3048A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE vehicule ADD CONSTRAINT FK_292FFF1D7420A800 FOREIGN KEY (vehicule_detail_id) REFERENCES vehicule_detail (id)');
        $this->addSql('ALTER TABLE vehicule_detail ADD CONSTRAINT FK_AB5396B354733C01 FOREIGN KEY (vehicule_category_id) REFERENCES vehicule_category (id)');
        $this->addSql('ALTER TABLE vehicule_detail ADD CONSTRAINT FK_AB5396B38A72B23 FOREIGN KEY (vehicule_brand_id) REFERENCES vehicule_brand (id)');
        $this->addSql('ALTER TABLE vehicule_detail ADD CONSTRAINT FK_AB5396B3B9F2B47 FOREIGN KEY (vehicule_carburant_id) REFERENCES vehicule_carburant (id)');
        $this->addSql('ALTER TABLE vehicule_detail ADD CONSTRAINT FK_AB5396B3FEA7F9B2 FOREIGN KEY (vehicule_type_id) REFERENCES vehicule_type (id)');
        $this->addSql('ALTER TABLE vehicule_file ADD CONSTRAINT FK_E0988DFF727ACA70 FOREIGN KEY (parent_id) REFERENCES vehicule (id)');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE account_default_module DROP FOREIGN KEY FK_B982E9719B6B5FBA');
        $this->addSql('ALTER TABLE account_custom_module DROP FOREIGN KEY FK_A7AFCE9F9B6B5FBA');
        $this->addSql('ALTER TABLE alert DROP FOREIGN KEY FK_17FD46C19B6B5FBA');
        $this->addSql('ALTER TABLE alert DROP FOREIGN KEY FK_17FD46C1A832475A');
        $this->addSql('ALTER TABLE customer DROP FOREIGN KEY FK_81398E098802B2C1');
        $this->addSql('ALTER TABLE customer DROP FOREIGN KEY FK_81398E0942D23FF0');
        $this->addSql('ALTER TABLE customer DROP FOREIGN KEY FK_81398E09F95FDB7F');
        $this->addSql('ALTER TABLE form DROP FOREIGN KEY FK_5288FD4F9B6B5FBA');
        $this->addSql('ALTER TABLE form_annotation DROP FOREIGN KEY FK_278372669B6B5FBA');
        $this->addSql('ALTER TABLE form_template DROP FOREIGN KEY FK_265A9AC79B6B5FBA');
        $this->addSql('ALTER TABLE network DROP FOREIGN KEY FK_608487BC9B6B5FBA');
        $this->addSql('ALTER TABLE network_account DROP FOREIGN KEY FK_D98581CE9B6B5FBA');
        $this->addSql('ALTER TABLE notification_log DROP FOREIGN KEY FK_ED15DF29B6B5FBA');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D6499B6B5FBA');
        $this->addSql('ALTER TABLE user_group DROP FOREIGN KEY FK_8F02BF9D9B6B5FBA');
        $this->addSql('ALTER TABLE account DROP FOREIGN KEY FK_7D3656A4C6798DB');
        $this->addSql('ALTER TABLE account_type_default_permission DROP FOREIGN KEY FK_4456D3E1C6798DB');
        $this->addSql('ALTER TABLE alert_intervention DROP FOREIGN KEY FK_1349B9D193035F72');
        $this->addSql('ALTER TABLE alert DROP FOREIGN KEY FK_17FD46C1DA891D69');
        $this->addSql('ALTER TABLE alert DROP FOREIGN KEY FK_17FD46C15B1F2B51');
        $this->addSql('ALTER TABLE form DROP FOREIGN KEY FK_5288FD4F9395C3F3');
        $this->addSql('ALTER TABLE form_template DROP FOREIGN KEY FK_265A9AC79395C3F3');
        $this->addSql('ALTER TABLE site DROP FOREIGN KEY FK_694309E49395C3F3');
        $this->addSql('ALTER TABLE alert DROP FOREIGN KEY FK_17FD46C15FF69B7D');
        $this->addSql('ALTER TABLE form_file DROP FOREIGN KEY FK_18BE32075FF69B7D');
        $this->addSql('ALTER TABLE form_record DROP FOREIGN KEY FK_99DA4B3F5FF69B7D');
        $this->addSql('ALTER TABLE form_record_file_annotation DROP FOREIGN KEY FK_643D8A3343A3BB6B');
        $this->addSql('ALTER TABLE form_record_file_annotation DROP FOREIGN KEY FK_643D8A33A2A71957');
        $this->addSql('ALTER TABLE form DROP FOREIGN KEY FK_5288FD4FF2B19FA9');
        $this->addSql('ALTER TABLE form_template DROP FOREIGN KEY FK_265A9AC7F420ECA8');
        $this->addSql('ALTER TABLE alert_intervention DROP FOREIGN KEY FK_1349B9D18EAE3863');
        $this->addSql('ALTER TABLE intervention_user DROP FOREIGN KEY FK_822CCE8B8EAE3863');
        $this->addSql('ALTER TABLE account_default_module DROP FOREIGN KEY FK_B982E971AFC2B591');
        $this->addSql('ALTER TABLE account_custom_module DROP FOREIGN KEY FK_A7AFCE9FAFC2B591');
        $this->addSql('ALTER TABLE account_type_default_permission DROP FOREIGN KEY FK_4456D3E1AFC2B591');
        $this->addSql('ALTER TABLE module DROP FOREIGN KEY FK_C24262812469DE2');
        $this->addSql('ALTER TABLE network_account DROP FOREIGN KEY FK_D98581CE34128B91');
        $this->addSql('ALTER TABLE user_group_network DROP FOREIGN KEY FK_80A7EE034128B91');
        $this->addSql('ALTER TABLE notification_log DROP FOREIGN KEY FK_ED15DF2D0520624');
        $this->addSql('ALTER TABLE user_notification_type DROP FOREIGN KEY FK_CCFDA738D0520624');
        $this->addSql('ALTER TABLE account_type_default_permission DROP FOREIGN KEY FK_4456D3E1FED90CCA');
        $this->addSql('ALTER TABLE notification_type DROP FOREIGN KEY FK_34E21C13FED90CCA');
        $this->addSql('ALTER TABLE user_permission DROP FOREIGN KEY FK_472E5446FED90CCA');
        $this->addSql('ALTER TABLE form DROP FOREIGN KEY FK_5288FD4FF6BD1646');
        $this->addSql('ALTER TABLE site_vehicule DROP FOREIGN KEY FK_256240C7F6BD1646');
        $this->addSql('ALTER TABLE user_group_site DROP FOREIGN KEY FK_E77E9478F6BD1646');
        $this->addSql('ALTER TABLE alert DROP FOREIGN KEY FK_17FD46C1B03A8386');
        $this->addSql('ALTER TABLE alert DROP FOREIGN KEY FK_17FD46C1794E2304');
        $this->addSql('ALTER TABLE customer DROP FOREIGN KEY FK_81398E09B03A8386');
        $this->addSql('ALTER TABLE customer DROP FOREIGN KEY FK_81398E096885AC1B');
        $this->addSql('ALTER TABLE form DROP FOREIGN KEY FK_5288FD4FB03A8386');
        $this->addSql('ALTER TABLE form_record DROP FOREIGN KEY FK_99DA4B3FA76ED395');
        $this->addSql('ALTER TABLE form_record_file DROP FOREIGN KEY FK_9E4337D5B03A8386');
        $this->addSql('ALTER TABLE form_template DROP FOREIGN KEY FK_265A9AC7B03A8386');
        $this->addSql('ALTER TABLE intervention_user DROP FOREIGN KEY FK_822CCE8BA76ED395');
        $this->addSql('ALTER TABLE network DROP FOREIGN KEY FK_608487BCB03A8386');
        $this->addSql('ALTER TABLE notification_log DROP FOREIGN KEY FK_ED15DF2A76ED395');
        $this->addSql('ALTER TABLE site DROP FOREIGN KEY FK_694309E46885AC1B');
        $this->addSql('ALTER TABLE site DROP FOREIGN KEY FK_694309E4B03A8386');
        $this->addSql('ALTER TABLE user_permission DROP FOREIGN KEY FK_472E5446A76ED395');
        $this->addSql('ALTER TABLE user_notification_type DROP FOREIGN KEY FK_CCFDA738A76ED395');
        $this->addSql('ALTER TABLE user_group DROP FOREIGN KEY FK_8F02BF9DB03A8386');
        $this->addSql('ALTER TABLE user_group_member DROP FOREIGN KEY FK_23AE5EAAA76ED395');
        $this->addSql('ALTER TABLE user_log_last_read DROP FOREIGN KEY FK_F6F0B4E5A76ED395');
        $this->addSql('ALTER TABLE user_login DROP FOREIGN KEY FK_48CA3048A76ED395');
        $this->addSql('ALTER TABLE user_group_site DROP FOREIGN KEY FK_E77E94781ED93D47');
        $this->addSql('ALTER TABLE user_group_network DROP FOREIGN KEY FK_80A7EE01ED93D47');
        $this->addSql('ALTER TABLE user_group_member DROP FOREIGN KEY FK_23AE5EAA1ED93D47');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D6499D419299');
        $this->addSql('ALTER TABLE alert DROP FOREIGN KEY FK_17FD46C14A4A3511');
        $this->addSql('ALTER TABLE form DROP FOREIGN KEY FK_5288FD4F4A4A3511');
        $this->addSql('ALTER TABLE site_vehicule DROP FOREIGN KEY FK_256240C74A4A3511');
        $this->addSql('ALTER TABLE vehicule_file DROP FOREIGN KEY FK_E0988DFF727ACA70');
        $this->addSql('ALTER TABLE vehicule_detail DROP FOREIGN KEY FK_AB5396B38A72B23');
        $this->addSql('ALTER TABLE vehicule_detail DROP FOREIGN KEY FK_AB5396B3B9F2B47');
        $this->addSql('ALTER TABLE vehicule_detail DROP FOREIGN KEY FK_AB5396B354733C01');
        $this->addSql('ALTER TABLE vehicule DROP FOREIGN KEY FK_292FFF1D7420A800');
        $this->addSql('ALTER TABLE vehicule_detail DROP FOREIGN KEY FK_AB5396B3FEA7F9B2');
        $this->addSql('DROP TABLE account');
        $this->addSql('DROP TABLE account_default_module');
        $this->addSql('DROP TABLE account_custom_module');
        $this->addSql('DROP TABLE account_type');
        $this->addSql('DROP TABLE account_type_default_permission');
        $this->addSql('DROP TABLE alert');
        $this->addSql('DROP TABLE alert_intervention');
        $this->addSql('DROP TABLE alert_status');
        $this->addSql('DROP TABLE alert_type');
        $this->addSql('DROP TABLE customer');
        $this->addSql('DROP TABLE form');
        $this->addSql('DROP TABLE form_annotation');
        $this->addSql('DROP TABLE form_file');
        $this->addSql('DROP TABLE form_record');
        $this->addSql('DROP TABLE form_record_file');
        $this->addSql('DROP TABLE form_record_file_annotation');
        $this->addSql('DROP TABLE form_template');
        $this->addSql('DROP TABLE form_type');
        $this->addSql('DROP TABLE intervention');
        $this->addSql('DROP TABLE intervention_user');
        $this->addSql('DROP TABLE intervention_cancel_reason');
        $this->addSql('DROP TABLE intervention_endform');
        $this->addSql('DROP TABLE intervention_status');
        $this->addSql('DROP TABLE module');
        $this->addSql('DROP TABLE module_category');
        $this->addSql('DROP TABLE network');
        $this->addSql('DROP TABLE network_account');
        $this->addSql('DROP TABLE notification_log');
        $this->addSql('DROP TABLE notification_type');
        $this->addSql('DROP TABLE permission');
        $this->addSql('DROP TABLE refresh_tokens');
        $this->addSql('DROP TABLE site');
        $this->addSql('DROP TABLE site_vehicule');
        $this->addSql('DROP TABLE user');
        $this->addSql('DROP TABLE user_permission');
        $this->addSql('DROP TABLE user_notification_type');
        $this->addSql('DROP TABLE user_group');
        $this->addSql('DROP TABLE user_group_site');
        $this->addSql('DROP TABLE user_group_network');
        $this->addSql('DROP TABLE user_group_member');
        $this->addSql('DROP TABLE user_log_last_read');
        $this->addSql('DROP TABLE user_login');
        $this->addSql('DROP TABLE user_type');
        $this->addSql('DROP TABLE vehicule');
        $this->addSql('DROP TABLE vehicule_brand');
        $this->addSql('DROP TABLE vehicule_carburant');
        $this->addSql('DROP TABLE vehicule_category');
        $this->addSql('DROP TABLE vehicule_detail');
        $this->addSql('DROP TABLE vehicule_file');
        $this->addSql('DROP TABLE vehicule_type');
    }
}
